apiVersion: v1
kind: Service
metadata:
  name: multirobotservice
  namespace: multi-robotic-application
  labels:
    app: aws-ecr
spec:
  selector:
    app: aws-ecr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
